config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'months#show'  
  resources :members, only: [:new, :create]
  resources :years, only: [:show] do
    resources :months, only: [:show] do
      resources :categories2, only: [:index] do
        resources :details2, only: [:index]
      end
      resources :days, only: [:show]
      resources :members, only: [:index, :show] do
        resources :categories, only: [:show] do
          resources :details, only: [:show, :create] do
            resources :howmuches, only: [:create, :destroy]
          end
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :details
  has_many :howmuches
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :category
  has_many   :howmuches
end

app/models/howmuch.rb
class Howmuch < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  belongs_to :detail, optional: true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :howmuches
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: {maximum: 8}
  validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_toform
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def set_toform
    @members = Member.where(user_id: current_user.id) if user_signed_in?
    @categories = Category.all
    @details = Detail.all
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/categories2_controller.rb
class Categories2Controller < ApplicationController
  def index
    gon.howmuch   = Category.all
    gon.howmuches  = Howmuch.where(user_id: current_user.id).all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @member = Member.where(id: params[:member_id])
    @details = Detail.all
    gon.howmuch   = Detail.all
    gon.howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(member_id: params[:member_id]).where(category_id: params[:id])
    
    @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(member_id: params[:member_id]).where(category_id: params[:id])
    @theyear = params[:year_id]
    @themonth = params[:month_id]
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def show
    gon.howmuch = Detail.all
    gon.howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id], params[:id]).all_day)
  end
end

app/controllers/details2_controller.rb
class Details2Controller < ApplicationController
  def index
    @category = Category.where(id: params[:categories2_id])
    gon.howmuch   = Member.all
    gon.howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(category_id: params[:categories2_id])
    @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(category_id: params[:categories2_id])
    @theyear = params[:year_id]
    @themonth = params[:month_id]
    respond_to do |format|
      format.html
      format.json
    end
  end
  def show
    @category = Category.where(id: params[:categories2_id])
    gon.howmuch   = Member.all
    gon.howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(category_id: params[:categories2_id])
    @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(category_id: params[:categories2_id])
    @theyear = params[:year_id]
    @themonth = params[:month_id]
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_member, :set_category, :set_detail


  def show
    @howmuch   = Howmuch.new
    @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(member_id: params[:member_id]).where(detail_id: params[:id]).order(when: "DESC")
    @theyear = params[:year_id]
    @themonth = params[:month_id]
    respond_to do |format|
      format.html
      format.json
    end
  end


  
  private
  def set_member
    @member = Member.find(params[:member_id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_detail
    @detail = Detail.find(params[:id])
  end
end

app/controllers/howmuches_controller.rb
class HowmuchesController < ApplicationController 
  def create
    @howmuch = Howmuch.new(howmuch_params)
    if @howmuch.save
      redirect_to year_month_member_category_detail_path(year_id: params[:year_id], month_id: params[:month_id], id: params[:detail_id])
    else
    end
  end

  def destroy
    howmuch = Howmuch.find(params[:id])
    if howmuch.destroy
      redirect_to year_month_member_category_detail_path(year_id: params[:year_id], month_id: params[:month_id], id: params[:detail_id])
    else
    end
  end


  private
  def howmuch_params
    params.require(:howmuch).permit(:name, :money, :where, :when, :user_id).merge(member_id: params[:member_id], category_id: params[:category_id], detail_id: params[:detail_id])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    gon.howmuch = Member.all
    gon.howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month)

    @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month)
    @theyear = params[:year_id]
    @themonth = params[:month_id]
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def show
    @member = Member.where(id: params[:id])
    @categories = Category.all
    gon.howmuch = Category.all
    gon.howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(member_id: params[:id])

    @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:month_id]).all_month).where(member_id: params[:id])
    @theyear = params[:year_id]
    @themonth = params[:month_id]
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to root_path, notice: '完了'
    else
      render :new
    end
  end

  private
  def member_params
    params.require(:member).permit(:name, :user_id)
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def show
    gon.howmuch = Category.all
    gon.howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(Date.today.year, Date.today.month).all_month)

    if params[:year_id]
      @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(params[:year_id], params[:id]).all_month)
      @theyear = params[:year_id]
      @themonth = params[:id]
    else 
      @howmuches = Howmuch.where(user_id: current_user.id).where(when: Time.local(Date.today.year, Date.today.month).all_month)
      @theyear = Date.today.year
      @themonth = Date.today.month
    end
    respond_to do |format|
      format.html
      format.json
    end
  end
  
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.haml
#calendar
.container
  .left--title
    %h1 
      = @member[0].name
  = render './myChart'
  = render './toform'

app/views/categories2/index.html.haml
.container
  %h2 Chart.js
  = render './myChart'
  = render './toform' 

app/views/days/show.html.haml
.container
  %h2 Chart.js
  = render './myChart'
  = render './toform' 

app/views/details/show.html.haml
%h1{class: "detailtitle"}
  = @member.name + 'の' + @detail.name + '費'
#calendar
.container
  .detail
    .howmuchlist
      %table.howmuchtable{border: 1}
        %tr
          %th.thdetail 項目
          %th.thmoney 値段 
          %th.thwhere 場所
          %th.thwhen 日時
          %th.thdelete
        - @howmuches.each do |howmuch|
          %tr
            %td 
              = howmuch.name
            %td 
              = howmuch.money.to_s(:delimited) + "円"
            %td 
              = howmuch.where
            %td
              = howmuch.when
            %td
              = link_to "削除", year_month_member_category_detail_howmuch_path(detail_id: params[:id], id: howmuch.id), method: :delete
    .form
      = form_for [@year, @month, @member, @category, @detail, @howmuch], url:year_month_member_category_detail_howmuches_path(detail_id: params[:id]) do |f|
        .howmuch-form
          = f.text_field :name, placeholder: "項目"
          = f.text_field :money, placeholder: "値段"
          = f.text_field :where, placeholder: "場所"
          = f.text_field :user_id, type: "hidden", value: current_user.id


        .input-group{"data-target-input" => "nearest"}
          = f.text_field :when, id: "created_at", class: "form-control datepicker", data: { target: '#created_at'}
          .input-group-append{"data-target" => "#created_at", "data-toggle" => "datetimepicker"}
            .input-group-text
              %i.fa.fa-calendar
        = f.submit value: "登録する", class:"createhowmuch"

app/views/details2/index.html.haml
#calendar
.container
  .left--title
    %h1
      = @category[0].name
  = render './myChart'
  = render './toform' 
%input{name:"category", type: "hidden", value: @category[0].id , class: "category hidden"}

app/views/layouts/_header.html.haml
.header
  .header__left.box
  .header__center.box
    = link_to "Z∀IW", root_path, class: "title"
  .header__right.box
    - if user_signed_in?
      = link_to "ログアウト", destroy_user_session_path, method: :delete
    - else
      = link_to "ログイン", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Money
    = include_gon(watch: true)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"}

  %body
  = render 'layouts/header'
  = yield
  %input{name:"theyear", type: "hidden", value: @theyear , class: "theyear hidden"}
  %input{name:"themonth", type: "hidden", value: @themonth , class: "themonth hidden"}

app/views/members/index.html.haml
#calendar
.container
  .left--title
    %h1 
      メ
      %br ン
      バ
      %br │
      別
  = render './myChart'
  = render './toform' 

app/views/members/new.html.haml
.devise-container
  = form_for @member do |f|
    .devise-container__upper
      %h2 メンバーを追加する
    .devise-container__lower
      .devise-container__lower--inner
        .email.form
          名前
          = f.text_field :name, placeholder: "名前を入力してください", class:"block"
          = f.text_field :user_id, type: "hidden", value: current_user.id
        .form
          = f.submit "メンバーを追加", class: "button block"

app/views/members/show.html.haml
#calendar
.container
  .left--title
    %h1 
      = @member[0].name
  = render './myChart'
  = render './toform' 
  

app/views/months/show.html.haml
#calendar
.container
  .left--title
    %h1 
      カ
      %br テ
      ゴ
      %br リ
      別
  = render './myChart'
  = render './toform' 
    

- @howmuches.each do |howmuch|
  %input{name:"howmuches", type: "hidden", value: howmuch.money , class: "howmuches hidden"}

app/views/years/show.html.haml
.container
  %h2 Chart.js
  %div
    %canvas#myChart